# Generated by Django 3.1.7 on 2021-05-29 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mobiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mbl_name', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=10)),
                ('brand', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('img1', models.ImageField(upload_to='')),
                ('img2', models.ImageField(upload_to='')),
                ('img3', models.ImageField(upload_to='')),
                ('color', models.CharField(max_length=50)),
                ('os', models.CharField(max_length=50)),
                ('memory', models.CharField(max_length=50)),
                ('display', models.CharField(max_length=50)),
                ('camera', models.CharField(max_length=50)),
                ('battery', models.CharField(max_length=50)),
                ('processor', models.CharField(max_length=50)),
                ('rating', models.CharField(max_length=10)),
            ],
        ),
    ]
