# Generated by Django 3.1.7 on 2021-05-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_mobiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobiles',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='mobiles',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
