# Generated by Django 3.1.7 on 2021-05-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20210529_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobiles',
            name='rating',
            field=models.FloatField(),
        ),
    ]
