# Generated by Django 3.2.3 on 2021-05-30 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20210530_0945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobiles',
            old_name='orders',
            new_name='order',
        ),
    ]
